### ISSUE TITLE
Appendix B.1 FCS_RADSEC_EXT

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#11]
**Questions for NIAP**
Looking for the origin of requirements _.1_-_.3_

**Comment by jfisherbah** [comment]
The RadSec requirements .1 and .2 were originally added in NIAP TD0271, issued on 4/26/18. Beyond that the origins of the requirements are unknown (i.e. I don't know whether they were added based on TC proceedings, on NIAP consultation with SME, on a TRRT response to a technical query, etc.). 

.3 was taken from what the TD called FCS_RADSEC_EXT.2.4 because it’s not correct to have an individual SFR element within a component only apply conditionally. This was therefore broken out into its own SFR component.

**Comment by kgal** [comment]
As @jfisherbah seems to have adequately answered the original question, I am closing this issue.
