### ISSUE TITLE
Appendix A.1 FPT_ITT.1 Basic Internal TSF Data Transfer Protection

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#12]
**Comment**
TLS 1.2 should be the threshold, 1.3 an objective goal.

**Comment by jfisherbah** [comment]
This would likely need to be handled through changes to the NDcPP because FPT_ITT.1 is inherited from the NDcPP and the NDcPP doesn’t currently define anything for TLS 1.3. If we want to make TLS 1.3 selectable in WLAN AS, we need to modify the Base-PP definitions of FCS_TLSC_EXT.1 and FCS_TLSS_EXT.1 to make TLS 1.3 selectable as well as any other SFR/EA changes that would go along with that.

**Comment by kgal** [comment]
The proposed resolution does not affect this document, so I am closing this issue.
