### ISSUE TITLE
FTP_ITC.1 Inter-TSF Trusted Channel

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#2]
**Comment**
Update verbiage to reflect WPA3 inclusion.

**Auditable Event**
WPA2 Connection with device previously utilizing a WPA3 connection (downgrade).

**Comment by jfisherbah** [comment]
Per SME feedback, auditable event for downgrade is WIDS related and should be considered out of scope for WLAN AS. 

Proposed WPA3 related updates are as follows:

a.	Modify FTP_ITC.1 in section 5.1.1.3 to remove 802.11 references
FTP_ITC.1.1 The TSF shall be capable of using **IEEE 802.1X, [selection: IPsec, RADIUS over TLS], and [selection: SSH, TLS, DTLS, HTTPS, no other protocols]** to provide a trusted communication channel between itself and authorized IT entities supporting the following capabilities: **802.1x authentication server**, audit server, [selection: authentication server, [assignment: other capabilities], no other capabilities] that is logically distinct from other communication channels and provides assured identification of its end points and protection of the channel data from disclosure and detection of modification of the channel data.

Application Note: This requirement has been modified from its definition in the NDcPP to mandate the communications protocols and environmental components that a WLAN Access System must use for infrastructure communications (802.11 support is also required for wireless client communications but this is covered by the FTP_ITC.1/Client iteration in section 5.2). IPsec or RADIUS over TLS (commonly known as "RadSec") is required at least for communications with the 802.1X authentication server. Other selections may be made if needed by other parts of the TSF. The requirement implies that not only are communications protected when they are initially established, but also on resumption after an outage.
The IT entity of "802.1X authentication server" is distinct from "authentication server" because the latter may be used for administrator authentication rather than authorization of WLAN clients.

If "IPsec" is selected in FTP_ITC.1.1, then FCS_IPSEC_EXT.1 from the NDcPP must be claimed. If RADIUS over TLS is selected in FTP_ITC.1.1, then FCS_RADSEC_EXT.1 in this PP-Module must be claimed, as well as FCS_TLSC_EXT.1 from the NDcPP.
FTP_ITC.1.2 The TSF shall permit the TSF or the authorized IT entities to initiate communication via the trusted channel.
FTP_ITC.1.3 The TSF shall initiate communication via the trusted channel for [assignment: list of services for which the TSF is able to initiate communications].

b.	Define 802.11 capability as new iteration in section 5.2
**FTP_ITC.1/Client Inter-TSF Trusted Channel (WLAN Client Communications)**
FTP_ITC.1.1/Client The TSF shall be capable of using **WPA3-Enterprise, WPA2-Enterprise and [selection: WPA3-SAE WPA2-PSK, no other mode] as defined by IEEE 802.11-2020** to provide a trusted communication channel between itself and WLAN clients that is logically distinct from other communication channels and provides assured identification of its end points and protection of the channel data from disclosure and detection of modification of the channel data.

FTP_ITC.1.2/Client The TSF shall permit **the authorized IT entities** to initiate communication via the trusted channel.

FTP_ITC.1.3/Client The TSF shall initiate communication via the trusted channel for [_no services_].

c.	Add FTP_ITC.1/Client to consistency rationale in section 6.1.4
FTP_ITC.1/Client This SFR iterates the FTP_ITC.1 SFR defined in the Base-PP to define trusted communication channels for the functionality that is specific to this PP-Module.

d.	Change the FTP_ITC.1 reference in Table 2 to FTP_ITC.1/Client

e.	Add FTP_ITC.1/Client mapping to O.AUTHENTICATION 
FTP_ITC.1/Client supports the objective by requiring the TSF to identify the trusted communications channels it implements for WLAN Client communications, each of which is able to support authentication.

**Comment by kgal** [comment]
For FTP_ITC.1.3/Client suggestion above, is the text "[no services]" supposed to be an assignment or straight text or something?

**Comment by jfisherbah** [comment]
Keep brackets and manually italicize contents; the text in question is an assignment filled out by the PP author so the assignment convention should be used but without the "assignment: " prompt to show ST authors that the text has already been filled out for them.

**Comment by kgal** [comment]
Okay. This should be finished.
